// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlhuE-BJn5uwcQ04_4DhBbi_2F0yo_Tmc',
    appId: '1:1078630148752:web:4dfe538978ba56b24f0615',
    messagingSenderId: '1078630148752',
    projectId: 'autostrade-app',
    authDomain: 'autostrade-app.firebaseapp.com',
    storageBucket: 'autostrade-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqtM8IjHY51ytZZkbOJ6v1ixhuhxtjc8s',
    appId: '1:1078630148752:android:29327e1a96fa5f794f0615',
    messagingSenderId: '1078630148752',
    projectId: 'autostrade-app',
    storageBucket: 'autostrade-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhROT2huikRgO31cdC6QZ7lKS0kgeQzrE',
    appId: '1:1078630148752:ios:8e5316eb2783f9874f0615',
    messagingSenderId: '1078630148752',
    projectId: 'autostrade-app',
    storageBucket: 'autostrade-app.firebasestorage.app',
    iosBundleId: 'com.autostrad.autostrad',
  );
}
